apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: backend-api-common # Repository 이름으로 변경
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
    - name: backend-api-common # Repository 이름으로 변경
      port: 80
      targetPort: 80
  selector:
    app: backend-api-common # Repository 이름으로 변경
#  type: LoadBalancer
  type: ClusterIP